import Head from "next/head"
import styles from "@styles/Home.module.css"
import HeroSection from "@components/HeroSection"
import FeatureSection from "@components/FeatureSection"
import Footer from "@components/Footer"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeroSection />
        <FeatureSection />
        <Footer />
      </main>
    </div>
  )
}
