import Head from "next/head"
import HeroSection from "@components/HeroSection"
import FeatureSection from "@components/FeatureSection"
import Footer from "@components/Footer"
import Navigation from "@components/Navigation"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation />
        <HeroSection />
        <FeatureSection />
        <Footer />
      </main>
    </div>
  )
}
